### ISSUE TITLE
'Root path not part of initialize notification'

### ISSUE THREAD

**Issue by joohing** [SofusA/roslyn-language-server#33]
Hey, I get the following error. I use neovim and I setup the LSPs myself, so no lsp-config is involved. Error message:

```
       2 [ERROR][2024-10-04 04:28:20] .../vim/lsp/rpc.lua:770    "rpc"   "/Users/jonathansamsing/language-servers/roslyn-language-server/target/debug/roslyn-language-server"    "stderr"    "thread 'main' panicked at src/main.rs:94:22:                                      
       1 Root path not part of initialize notification: trailing characters at line 1 column 30                                                                                                                                                                                 
   38383 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                                                                                                                          
       1 "    
```

My neovim config is:

```
-- Roslyn
local roslyngroup = augroup("roslynls", {})
autocmd("FileType", {
    pattern = "cs",
    callback = function()
        local root_dir = vim.fs.dirname(
            vim.fs.find({ '.sln', '.csproj', '.git' }, { upward = true })[1]
        )
        local client = vim.lsp.start({
            name = 'roslyn',
            cmd = { 'Microsoft.CodeAnalysis.LanguageServer' },
            root_dir = root_dir,
        })
        vim.lsp.buf_attach_client(0, client)
    end,
    group = roslyngroup
})
```

I tried:
- Using nix
- Using cargo to build it from source
- Installing via cargo

**Comment by SofusA** [comment]
Could you send the output when running `roslyn-language-server` at the root of a csharp project? 

And which version of dotnet?

**Comment by joohing** [comment]
Dotnet version is 8.0.303, the command output above is the result of attempting to run it in the directory of a solution with ~20 projects

**Comment by SofusA** [comment]
Heh it would be nice to output the failed initialize notification on this type of error.

Could you try to create a new dotnet project with the template `dotnet new console` and see if you get the same error when running just `roslyn-language-server` from that directory?

**Comment by SofusA** [comment]
I think I know the issue. We used to expect `rootPath` to be part of the initialise notification. Neovim probably only provides `rootUri`. 
#30 have fixed this.  

Can you try again from main branch?

We should consider adding a default to the execution path if neither root path or root uri is provided. 

Thanks for helping debugging.

**Comment by joohing** [comment]
Sorry, didn't see your previous message in time - I'll try to run it from the main branch later today. 

And thanks to you for making this! Language servers become so much better when they actually, idk, follow the language server protocol 😂

**Comment by SofusA** [comment]
I found an issue for neovim and fixed it. 
You can see a simple config in the readme.
