### ISSUE TITLE
SLN file selection

### ISSUE THREAD

**Issue by Aridor2006** [SofusA/roslyn-language-server#70]
Hello,

I'm using this with Helix and was wondering how the solution file that is used is being selected. It works fine with most smaller projects, but in a big mono repo with many nested solutions it seems to be going to the top git? level and recurse through the folders alphabetically? and use the first sln find it finds, instead of using the sln file in the working directory. Is there some way to control this?

**Comment by Aridor2006** [comment]
Ok, seems to be a solved problem with Helix itself and I found a fix here: https://github.com/helix-editor/helix/pull/5748

**Comment by SofusA** [comment]
I actually did not know this. Thanks!
